spring.application.name=bytehub
spring.datasource.url=jdbc:postgresql://localhost:5432/bytehub
spring.datasource.username=bytehub_user
spring.datasource.password=bytehub_pass
spring.jpa.hibernate.ddl-auto=update